### ISSUE TITLE
beneos-module (former beneos_module) libwraper changes

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#109]
As I told I changes the module name from `beneos_module` to `beneos-module` since the FoundryVTT only accepts - in order to get whitelisted for the Foundry module browser.

It seems there are some hardcoded references to `beneos_module` (for example libwrapper). Can you fit that please?

![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/129e4dab-4467-4161-82a5-ca6f72fcc50d)

**Comment by LeRatierBretonnien** [comment]
Should be fixed now.
