### ISSUE TITLE
Beneos Module: After Compendium Import you need to F5 in order to drag and drop a token onto the canvas

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#115]
After you made a scan with the beneos module you need to F5 in order to be able to drag and drop an token into your world. We already got some reports on discord because users think it is not working.

https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/5c8b139f-79de-4b5a-a707-f882708a77db

**Comment by LeRatierBretonnien** [comment]
Fixed
