### ISSUE TITLE
Unknown error messages when rebuilding compendium 

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-module#116]
<img width="562" alt="ratier" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/f03a2809-a838-4f42-9fa0-ec4d2b31b73c">

when rebuilding compendium, this unknown error appears after every entry after no. 137 multiple times. no issues oocur during the rebuild and everything works as intended, as far as I can see.

**Comment by LeRatierBretonnien** [comment]
This is 100% related to DD5 actors. Something has probably changed between DD5 system versions. 
Try this : 
1 - Import the actor from the compendium into the world
2 - Export the actor with the JSON export function of Foundry
3 - Import again the actor in a fresh new DD5 world 
=> do you still have the error ?

If yes, I recommend to ask this to the DD5 system development team at Foundry, it is not related to the module itself.

**Comment by LeRatierBretonnien** [comment]
Issue due to comma character (",") inside some fields of the actor -> not module related
