### ISSUE TITLE
Search Engine: Item Result Form Design

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#12]
Final Design:
![Item Overview Clean](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/8c27e1cc-5de0-4336-a1b4-c455a402fa62)

Explanation:
![search_engine_form_item_explanation](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/6bb71648-d41e-4cb0-8b76-bc61d35ff198)

**0 A - Result Item Box**
- Image: `result_form_bg.webp`
- Width: **New** `724 px` Old -> `1237 px`
- height: **New** `596 px `Old ->`1350 px`

**0 B - Result Item Box Loop**
- Image: `result_form_bg_loop.webp`
- Width: `724 px` Old
- height: `1px `Old

**0 B - Result Item Box Title Bar Alone**
- Image: `result_form_bg_title_bar.webp`
- Width:  `724 px` Old
- height: `1px `Old

**0 B - Result Item Box Bottom Alone**
- Image: `result_form_bg_bottom.webp`
- Width: `724 px` Old
- height: `24 px `Old

**1 - Search result Item Background [Not Selected]**
- Color: `#eaeaea`

**2 - Search Result Item Icon On top of no. 13**
- Image: `***-icon.webp`

**3 - Search result Item Background [Not Selected]**
Info: The color change when an item is mouseovered. The Selector Arrows at the side should also appear (No. 5)
- Color: `#d5c8c3`

**4 - Description Text Box**
Info: The text Box shall beginn under the Icon (No. 2) to make it look connected
- Text Color: `#3e0706`
- Text Box BG Color: `#ebe8e0`
- Text Box Stroke Color: `#68665e `
- Text Box Stroke Size: `1 px `

**5 - Search Result Selector**
Info: The selectors should be visible wenn an Item is mouseovered.
> Image: `search_selector.webp`

**6 - Right Side Shaped Text Boxes**
Info: This is the Textbox for "Installed", "Tier" and "Value"
- Text Color:` #191813`
- Text Box BG Color: `#ebe8e0`
- Image 1:` right_box_bg.webp, Width: 2x Height: 41px`
- Image 2: `right_box_end.webp, Width: 34px Height: 41px`

**7 - Search Result title**
Info 1: The Box shall beginn under the Icon (No. 2) to make it look connected
Info 2: The length of the box is flexible based on the length of the item name.
Info 2: If the Item text is too long it gets cutted off with "..." at the end. -> "SuperLongItemText..."
- Text Color: `#191813`
- Text Box BG Color: `#3e0706`
- Image 1: `result_title.webp, Width: 2px Height: 63px`
- Image 1: `result_title_end.webp, Width: 34px Height: 63px`

**8 - Origin icon**
Info: Here the set Item Icon defined in "origin": "" is displayed
- Images: `\beneos-database\common\thumnbails`

**9 - Result Form BG**

- Content starts from left: `29 px`
- Content starts from top: `116 px`
- Content starts from down: `29 px`
- Content starts from right: `39 px`
- Image 1: `result_form_bg.webp`

**10 - Search Result title bg gradient**
Info 1: The gradient starts at the exact same position as Search Result title (No. 7)
- Image: `result_title_bg_gradient.webp`

**11 - Search Result Icon BG**
Info 1: This Item is displayed Below the item icon. Providing a small border and servers as fall back in case an image can not be displayed correctly
- Image: `result_item_icon_bg.webp, Width: 229px Height: 229px`

**12 - Search Result Top Border**
Info 1: This border starts below the Search Reult Icon BG (No. 11) from the top left corner of the icon all the way to the right
- Image: `border_top.webp`, **New**: ` Width: 546 px Height: 3px`  Old: -> Width: 984px Height: 3px

**13 - Search Result bottom Border**
Info 1: This border starts below the Search Reult Icon BG (No. 11) from the bottom left corner of the icon all the way to the right end of the entire result box
- Image: border_bottom.webp, **New**: `Width: 682 px Height: 3px`   Old -> : `Width: 1237px Height: 3x`

**14 - Result Form Title**
Info 1: This Title is placed above Result Form title Bar (No. 9). BEcause of its drop shadow and other effects it is an image not a font.
- Image: `result_form_title_item.webp, Width: 476px Height: 36x`

**15 - Attunement Text Box**
Info 1: This Text Box was moved from the right side to make space for the origin Icon (No. 8)

**Download the slices HERE**
[item_result_form_slices.zip](https://github.com/BeneosBattlemaps/beneos_module/files/12269822/item_result_form_slices.zip)

**Comment by LeRatierBretonnien** [comment]
Can be closed I think
