### ISSUE TITLE
Beneos Module - Static <-> Animated Map Switcher: Bug - Scene Context Menu 

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#127]
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/cc14710c-927d-4035-885c-6d9a5a9eaab7)

![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/1acf363e-ac14-4cc5-8591-c94e13674561)

If you right click on a scene in your scene browser that has NO static images available (any other non beneos map) Foundry throws an error and no context menu appears leading to not being able to switch to any non-Beneos Map.

[localhost-1706005226867.log](https://github.com/BeneosBattlemaps/beneos-module/files/14022136/localhost-1706005226867.log)

**Comment by LeRatierBretonnien** [comment]
Fixed in next push
