### ISSUE TITLE
Beneos Search: Items can't be dragged and dropped into new 5e PC sheet (DnD V3)

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-module#132]
<img width="1792" alt="ratier3" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/cbcb2ce3-59ae-4e8b-8f0d-2f78911f118e">

when you try to drag an item from the search engine into the PC's inventory, it does not complete the action and the following error message apperars:
<img width="674" alt="ratier 4" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/8374ca52-7f5a-4fe8-8001-0ec64a10cf41">

dragging a spell from the database into the new PC sheet's spellbook works flawlessly, fyi.

**Comment by LeRatierBretonnien** [comment]
Unable to test, I have no more valid installed Items & Spells. Please provide me a few data to test

**Comment by LeRatierBretonnien** [comment]
Tested with the items provided and the latest DD5 system : 
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/7b65bb74-bab2-4224-882a-e2776d2fe49b)

It works....

**Comment by LeRatierBretonnien** [comment]
Well.. it works
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/dd9b3f26-6f4c-4617-b6fd-07fa3ca4bd03)

**Comment by LeRatierBretonnien** [comment]
Can be closed I think
