### ISSUE TITLE
Beneos Tokens: Display Journal Button is missing

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-module#134]
![grafik](https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/6ece5e14-cd2c-426c-9937-940434e64986)

The button that lets the DM show the 360° intro contained in the creature's journal seems to be missing.

**Comment by LeRatierBretonnien** [comment]
Which token ? Seems to work for me, tested on 5 different tokens
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/b6cf705c-6290-4878-ad6f-f791dbcc98fd)

**Comment by LeRatierBretonnien** [comment]
Note that it seems to me than many links are broken in the journal video/PDF

**Comment by beneos-leon** [comment]
In what way are they broken? the journal json itself seems to be without syntax errors. can you test with the latest token (150_ravager)?

**Comment by LeRatierBretonnien** [comment]
Taken from my local data : 
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/310b1881-76ca-4b4b-be93-c768637dc72d)

So at least, on my side, URL are wrong.

**Comment by LeRatierBretonnien** [comment]
The issue is due to this : 
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/e9883983-20bf-4df1-a054-c4ec88d78bda)

As you removed IDs from name, it must be now : 
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/1085008/ad83d33c-ec6a-48d7-85f8-a63db71d3b05)

**Comment by LeRatierBretonnien** [comment]
I pushed a change that will manage this case : if the journal is not found in a first place, the module tries to detect it again by removing the IDs in front of the name.
Pushed and available in github
