### ISSUE TITLE
[PF2Ee] Module impacting character sheet rendering

### ISSUE THREAD

**Issue by NPAO-Pan** [BeneosBattlemaps/beneos-module#135]
Beneos module (confirmed to not be one of the other module dependencies) impacting Pathfinder 2e character sheets.  Scrollable panel elements in spell and inventory sections (but not Feats) are not scaling correctly and are rendered mostly unusable by players.  Images are shown below.  No overt errors related to sheet rendering identifiable through console.

![image](https://github.com/BeneosBattlemaps/beneos-module/assets/155191756/ba654cb3-5fd6-41b2-ab92-c30f4f2497af)
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/155191756/c50c9cd7-9674-44ab-9912-b9de31d001ba)

**Comment by LeRatierBretonnien** [comment]
Unable to reproduce on my side. Are you sure that if they disable the beneos_module (and only it), the problem disappear ?

**Comment by LeRatierBretonnien** [comment]
Found and fixed ! CSS conflicts rules

**Comment by NPAO-Pan** [comment]
Thank you for looking into this and the quick fix!  Resolution confirmed on user side.  :)
