### ISSUE TITLE
Beneos Tokens: "The token key see seems wrong" Error reappears

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-module#138]
What does it do?
**This error prevents opening the menu to scale  the token or switch animations or show the preview video**
**This error randomly appears for users as well and we can't reliably replicate it**
This error usually coincides with errors in either the import script or the token config json, but i couldn't locate any

What does it not do?
This error **does NOT** prevent the correct import or rebuild of the compendium
This error **does NOT** prevent other tokens from being scaled or have their token journal preview video shown

What did I already try?
- deleted all actors, restarted and reimported
- tried the same in different world
- tried the same in new, empty world

How does it look like?
Screenshot 1:
<img width="563" alt="Token Key Wrong" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/c1044d9f-c3a6-456d-98b7-e9fb259a867c">

Screenshot 2:
<img width="704" alt="Token Key Wrong 2" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/ea9ad443-6461-47c4-a9ca-b88117853833">

How does normal look like?
<img width="393" alt="normal" src="https://github.com/BeneosBattlemaps/beneos-module/assets/106017284/6b00a9b6-846d-4a43-abc5-98711aaeb35d">

JSON FILES of the affected token:

[actor_153_mummy_tomb_thrall_1.json](https://github.com/BeneosBattlemaps/beneos-module/files/14727758/actor_153_mummy_tomb_thrall_1.json)

[journal_153_mummy_tomb_thrall_1.json](https://github.com/BeneosBattlemaps/beneos-module/files/14727759/journal_153_mummy_tomb_thrall_1.json)

[tokenconfig_153_mummy_tomb_thrall_1.json](https://github.com/BeneosBattlemaps/beneos-module/files/14727760/tokenconfig_153_mummy_tomb_thrall_1.json)

**Comment by LeRatierBretonnien** [comment]
I understand the issue occurs ONLY with the above tokens. Am I right?

**Comment by beneos-leon** [comment]
At other points, it occured with other Tokens before. But at this point, it occurs only with the above token, correct.

**Comment by LeRatierBretonnien** [comment]
Error in tokenconfig file, the "key" must in the proper format, as indicated in Discord
