### ISSUE TITLE
Beneos Module V12 - globalThis.mergeObject Warning

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#142]
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/1bf674e9-4a6c-4d54-be0f-fd75fa1f359d)

With V12 I get this warning by just activating a Beneos Battlemap I downloaded with Moulinette. What does this mean and how to fix/prevent this so we don't have unwanted issues with V13/V14?

**Comment by LeRatierBretonnien** [comment]
This is 100% related to POI-teleport and Monk Active Trigger, nothing to do with beneos module. You must redirect the request/issue to the relevant repository.

**Comment by LeRatierBretonnien** [comment]
Can be closed also.
