### ISSUE TITLE
Beneos Module V12: TokenDocument5e#actorData Warning

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#143]
![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/1a9b303e-1e39-4bfd-9246-043e6afb6ffa)

When creating a simple default token in a V12 world with beneos battlemaps loaded (via moulinette) every time I move a troken I get this warning. What is this and has it something to do with the Beneos Module?

[localhost-1717528963566.log](https://github.com/user-attachments/files/15569444/localhost-1717528963566.log)

https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/1c993e77-6da3-4cf0-a76f-f73e54c17800

**Comment by LeRatierBretonnien** [comment]
This one is related to the BeneosModule, yes. Fix ongoing
