### ISSUE TITLE
Beneos MLT: Teleport is not working correctly

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#144]
When importing a Beneos Map pack via Moulinette the pre-placed MLT areas are not linked correctly. I attached a video showcasing a token moving into a MLT area but gets teleportet to a completely random location (not even another MLT area). Even though source<->Destination are both on the world and should work (see image). No Error Messages in the log.

https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/ce55ebc3-68d4-4256-a7b1-cbab92ba1ff1

**I noticed: If you have the two MLT Areas in the same scene, they are working. But if the destination is on another scene it wont teleport correctly**

![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/d977d1e3-1839-4a9c-be47-f050dcab50cd)

**Comment by BeneosBattlemaps** [comment]
I noticed: If you have the two MLT Areas in the same scene, they are working. But if the destination is on another scene it wont teleport correctly

**Comment by LeRatierBretonnien** [comment]
Fixed and available in  forked MLT
