### ISSUE TITLE
Beneos Module: Loading Bar for compendium building process

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#149]
Before we start with the "Beneos Cloud" project, we need to improve the user experience for the old method. Therefore, I'd like to have a progress bar for the compendium building process to show the users that something is happening. Most of the users do not open the console at all. Moulinette also has a progress bar as well.

![image](https://github.com/BeneosBattlemaps/beneos-module/assets/93905181/64714b63-ece6-4870-8b3f-75cff20f7a01)

I imagine one bar for every step. We know how many folders we have in the content array, so we can feed a progress bar with every imported token.
- 1 / 4 - Cleaning Existing Beneos Compendiums
- 2 / 4 - Collecting Beneos Tokens
- 3 / 4 - Collecting Beneos Items
- 4 / 4 - Collecting Beneos Spells

Is this possible?

**Comment by LeRatierBretonnien** [comment]
Progress of each item/actor/deletion is updated now dynamically in the chat messages.
