### ISSUE TITLE
Beneos Tokens - V12 - Right Click Buttons have no effect (besides the journal)

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#152]
![image](https://github.com/user-attachments/assets/190cde9f-17cc-4bb3-9df6-a25c89de6574)

The context menu buttons seem to not function. This was also reported by several different users. 

The right click itself does not throw erros. Clicking a button also seems to not throw errors in the console. 

There is however an error when a scene is loading that might (or might not) be related to this behavior. **In V11 all buttons work as expected**

![image](https://github.com/user-attachments/assets/42794ca0-4141-4503-ba62-fe3b38ce7ea9)

**Comment by LeRatierBretonnien** [comment]
Fix in the commit  above
