### ISSUE TITLE
New Feature: Also add Tokens | Items | Spells from the module folder to the compendium

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#44]
I want to offer the Beneos module via the official Foundry Module Browser. that means the module has to be useful for non-patrons as well. I would like to add a small selection of free content to the module that is installed directly with the module. This is mainly so called SRD material that includes official spells and items as well as a selection of Beneos tokens.

This means not only beneos_assets / ... must be taken into account during the scan, but always also the content in the module folder. I suggest that we also map there the same structure as in the data folder, but of course with much less items.

----------------

Je souhaite proposer le module Beneos via le navigateur officiel du module Foundry, ce qui signifie que le module doit également être utile pour les non-patrons. J'aimerais ajouter au module une petite sélection de contenus gratuits qui seront directement installés avec le module. Il s'agit principalement de matériel SRD, qui comprend des sorts et des objets officiels, ainsi qu'une sélection de tokens Beneos.

Cela ne signifie pas seulement beneos_assets / ... doit être pris en compte lors du scan, mais aussi le contenu du dossier module. Je propose que nous y reproduisions également la même structure que dans le dossier de données, mais bien sûr avec beaucoup moins d'objets.

Traduit avec www.DeepL.com/Translator (version gratuite)

**Comment by LeRatierBretonnien** [comment]
You must provide me the relevant compendiums. I will add them in the module.

**Comment by LeRatierBretonnien** [comment]
Can be closed I think
