### ISSUE TITLE
Moved: Bug: Failed to initialize Actor (IF STILL RELEVANT)

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos-module#5]
For three days we got several reports from different people having this error during compendium build. 

![image](https://github.com/BeneosBattlemaps/BeneosTokens/assets/93905181/142e98e2-0307-4919-960a-7852cb4c61a8)

I also encountered this issue in one of my worlds, It did not go away even when disabling the Beneos Module and deleting all actors and journals in the world. In another world I have not had any issues. That is weird. I attached mine and a Patrons Error Log

Here are links to their report in our troubleshooting discord
https://discord.com/channels/840218455193288714/840222617759514706/1122111459606937621
https://discord.com/channels/840218455193288714/840222617759514706/1113127452735197324
https://discord.com/channels/840218455193288714/840222617759514706/1112945222364700733
[jorgecomas.es-1687608558683.log](https://github.com/BeneosBattlemaps/BeneosTokens/files/11856885/jorgecomas.es-1687608558683.log)
[localhost-1687608534816.log](https://github.com/BeneosBattlemaps/BeneosTokens/files/11856886/localhost-1687608534816.log)

**Comment by LeRatierBretonnien** [comment]
I suspect this issue will no more arise with the removal of animations.

**Comment by LeRatierBretonnien** [comment]
Old issue, to be closed I think.
